AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Model provider

  Sample SAM Template for llm model provider

Globals:
  Function:
    Timeout: 180

Resources:
  ModelProviderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "prodv2"
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 500
            Period: WEEK
          Throttle:
            BurstLimit: 100
            RateLimit: 50
  ModelProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Timeout: 180
      Architectures:
        - x86_64
      Events:
        ModelInvoke:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ModelProviderApi
            Path: /model
            Method: post
            Auth:
              ApiKeyRequired: true
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-south-1:010526271896:secret:AnthropicAPIKey-yZA5FJ
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-south-1:010526271896:secret:GeminiAPIKey-cs2C4o
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-south-1:010526271896:secret:OpenAIAPIKey-TwhZXt
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-south-1:010526271896:secret:LLMFunctionUrlSecret-GjI811
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-south-1:010526271896:secret:LLMGWApiKeySecret-wlorzL
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./provider
      DockerTag: latest

Outputs:
  ModelProviderApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ModelProviderApi}.execute-api.${AWS::Region}.amazonaws.com/ProdV2/model/"

  ModelProviderApiKey:
    Description: "API Key for accessing the Model Provider API"
    Value: !Ref ModelProviderApiKey
